apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::234353605762:role/UdacityFlaskDeployCBKubectlRole
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::234353605762:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-09-27T11:00:42Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1756"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 2b9c4969-54bd-45a5-b0f8-0a04aaa78c0a
